import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { copyFileSync } from 'node:fs'

// src/notify/index.d.ts is hand-written (notify is plain JS/JSX, not compiled from TS),
// so it isn't generated by the build — just copied into dist/notify/ alongside the bundle.
function copyTypes() {
  return {
    name: 'copy-types',
    closeBundle() {
      copyFileSync('src/notify/index.d.ts', 'dist/notify/index.d.ts')
    },
  }
}

// Only `aw-kit/notify` needs a build. `aw-kit/eslint-rules` and the bin are plain Node ESM
// served straight from src/ and bin/ (no JSX, no CSS), so they are not part of this bundle.
export default defineConfig({
  plugins: [react(), copyTypes()],
  build: {
    outDir: 'dist/notify',
    lib: {
      entry: 'src/notify/index.js',
      formats: ['es'],
      fileName: () => 'index.js',
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        assetFileNames: (assetInfo) =>
          assetInfo.name?.endsWith('.css') ? 'style.css' : assetInfo.name,
      },
    },
    cssCodeSplit: false, // force single dist/notify/style.css instead of per-chunk splitting
  },
})
