import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { copyFileSync } from 'node:fs'

// src/index.d.ts is hand-written (this package is plain JS/JSX, not compiled from TS),
// so it isn't generated by the build — just copied into dist/ alongside the bundle.
function copyTypes() {
  return {
    name: 'copy-types',
    closeBundle() {
      copyFileSync('src/index.d.ts', 'dist/index.d.ts')
    },
  }
}

export default defineConfig({
  plugins: [react(), copyTypes()],
  build: {
    lib: {
      entry: 'src/index.js',
      formats: ['es'],
      fileName: () => 'aw-notify-kit.js',
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        assetFileNames: (assetInfo) =>
          assetInfo.name === 'aw-notify-kit.css' ? 'style.css' : assetInfo.name,
      },
    },
    cssCodeSplit: false, // force single dist/style.css instead of per-chunk splitting
  },
})
